<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRztioi6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRztioi6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRztioi6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRztioi6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRztioi6\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rztioi6',
    'container.build_id' => 'fcedfbed',
    'container.build_time' => 1546369322,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRztioi6');
